### ISSUE TITLE
Redesign login screen

### ISSUE THREAD

**Issue by kevinyou77** [kevinyou77/Swordfish#1]
The login screen is pretty barebones, needs more polish.

**Comment by aKANJx** [comment]
Do you have any idea how it needs to be?

**Comment by aKANJx** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2019-10-22 at 16 13 53](https://user-images.githubusercontent.com/6733270/67322537-88b9a000-f4e7-11e9-933b-5fe76d4fca7c.png)

Is it better? What you think?
https://github.com/kevinyou77/Swordfish/pull/17

**Comment by kevinyou77** [comment]
I think it looks great! Thank you for your contribution!
